# Generated by Django 3.2.4 on 2021-09-19 12:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('open_or_close', models.CharField(choices=[('o', 'Open'), ('c', 'Close')], max_length=15)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='cities.university')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('number_of_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='You should write +996[code][number]', regex='^(\\+996)\\d{9}$')])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_faculty', to='fakultet.faculty')),
            ],
        ),
    ]
