# Generated by Django 3.2.4 on 2021-08-27 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('open_or_close', models.CharField(choices=[('o', 'Open'), ('c', 'Close')], max_length=15)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='cities.university')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
