# Generated by Django 3.2.4 on 2021-08-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakultet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='open_ot_close',
            field=models.CharField(choices=[('o', 'Open'), ('c', 'Close')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
