# Generated by Django 3.2.4 on 2021-08-15 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakultet', '0002_faculty_open_ot_close'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_image', to='fakultet.faculty')),
            ],
        ),
    ]
