# Generated by Django 3.2.4 on 2021-08-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakultet', '0003_facultyimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyImage',
        ),
    ]
