# Generated by Django 3.2.4 on 2021-07-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakultet', '0003_alter_faculty_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='slug',
        ),
    ]
