# Generated by Django 3.2.4 on 2021-08-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakultet', '0004_alter_application_number_of_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='number_of_phone',
            field=models.IntegerField(),
        ),
    ]
