# Generated by Django 3.2.4 on 2021-08-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakultet', '0004_delete_facultyimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='open_ot_close',
            new_name='open_or_close',
        ),
    ]
