# Generated by Django 3.2.4 on 2021-09-19 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='город')),
                ('description', models.TextField()),
                ('population', models.IntegerField()),
                ('date_of_born', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_born', models.DateField(blank=True, null=True)),
                ('university', models.CharField(max_length=255, verbose_name='унивеститет')),
                ('description', models.TextField()),
                ('number_of_people', models.IntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='univer', to='cities.city')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UniversityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='city', verbose_name='Картинки')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_image', to='cities.university')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='city', verbose_name='Картинки')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_image', to='cities.city')),
            ],
        ),
    ]
