# Generated by Django 3.2.4 on 2021-08-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('-id',)},
        ),
    ]
