# Generated by Django 3.2.4 on 2021-08-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityimage',
            name='date_of_born',
            field=models.DateField(blank=True, null=True),
        ),
    ]
