# Generated by Django 3.2.4 on 2021-08-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_cityimage_date_of_born'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityimage',
            name='date_of_born',
        ),
        migrations.AddField(
            model_name='city',
            name='date_of_born',
            field=models.DateField(blank=True, null=True),
        ),
    ]
