# Generated by Django 3.2.4 on 2021-08-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_auto_20210814_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='date_of_born',
            field=models.DateField(blank=True, null=True),
        ),
    ]
