# Generated by Django 3.2.4 on 2021-07-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_auto_20210702_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(default='defoult name', upload_to=''),
            preserve_default=False,
        ),
    ]
