# Generated by Django 3.2.4 on 2021-08-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_alter_university_date_of_born'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='universityimage',
            options={'ordering': ['-id']},
        ),
    ]
