# Generated by Django 3.2.4 on 2021-07-03 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_city_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='image',
        ),
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='city', verbose_name='Картинки')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_image', to='cities.city')),
            ],
        ),
    ]
