# Generated by Django 3.2.4 on 2021-07-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_auto_20210703_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(default='def name', upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CityImage',
        ),
    ]
