# Generated by Django 3.2.4 on 2021-07-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0007_auto_20210703_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ('-id',)},
        ),
    ]
