# Generated by Django 3.2.4 on 2021-07-04 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0008_auto_20210704_0722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={},
        ),
        migrations.RemoveField(
            model_name='city',
            name='image',
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='city', verbose_name='Картинки')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_image', to='cities.city')),
            ],
        ),
    ]
