# Generated by Django 3.2.4 on 2021-07-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0009_auto_20210704_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(default='defoult text'),
            preserve_default=False,
        ),
    ]
