# Generated by Django 3.2.4 on 2021-07-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_university_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='slug',
        ),
    ]
