# Generated by Django 3.2.4 on 2021-09-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_city_options'),
        ('favourite', '0002_auto_20210903_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='university',
        ),
        migrations.AddField(
            model_name='favourite',
            name='university',
            field=models.ManyToManyField(related_name='university_favourite', to='cities.University'),
        ),
    ]
